name: flib
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.18.0
  uuid: ^3.0.7
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  device_info_plus: ^11.3.3
  connectivity_plus: ^6.1.3
  internet_connection_checker_plus: ^2.7.1
  package_info_plus: ^8.3.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  flutter_secure_storage: ^9.0.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
